name: Release-Development
on:
  workflow_dispatch:
    inputs:
      compiler:
        type: choice
        description: What compiler to use?
        required: true
        default: YYC
        options:
          - YYC
          - VM
  push:
    branches:
      - release/0.9

jobs:
  build_needed:
    name: Build needed?
    runs-on: ubuntu-latest
    outputs:
      needed: ${{ steps.commit_check.outputs.needed }}  # Output for skipping
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Check commit
        id: commit_check
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Merge commit message: $COMMIT_MESSAGE"

          EXCLUDE_PATTERN="^(docs|chore|style|ci)"

          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manually triggered, forcing build."
            echo "needed=true" >> $GITHUB_OUTPUT
          elif echo "$COMMIT_MESSAGE" | grep -Eq "$EXCLUDE_PATTERN"; then
            echo "Commit message matches excluded pattern, skipping build."
            echo "needed=false" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "needed=true" >> $GITHUB_OUTPUT
          fi

  gamemaker_build:
    name: Build
    uses: ./.github/workflows/gamemaker_build.yml
    secrets: inherit
    needs: build_needed
    if: needs.build_needed.outputs.needed == 'true'
    with:
      yyc: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.compiler == 'YYC' || github.event_name != 'workflow_dispatch' }}

  prepare_release:
    name: Prepare dev-old tag
    runs-on: ubuntu-latest
    needs: gamemaker_build
    if: needs.build_needed.outputs.needed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if previous dev tag exists
        id: check_dev_tag
        run: |
          if git rev-parse --verify "refs/tags/dev/${{ github.ref_name }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set dev-old tag to current dev tag (if exists)
        if: steps.check_dev_tag.outputs.exists == 'true'
        run: |
          prev_sha=$(git rev-parse "refs/tags/dev/${{ github.ref_name }}")
          echo "Updating dev-old/${{ github.ref_name }} to $prev_sha"
          git tag -f "dev-old/${{ github.ref_name }}" "$prev_sha"
          git push -f origin "refs/tags/dev-old/${{ github.ref_name }}"

  release:
    name: Release
    runs-on: windows-2022
    needs: [gamemaker_build, prepare_release]
    if: needs.build_needed.outputs.needed == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Download built file artifact
        uses: actions/download-artifact@v4
        with:
          name: built-file
          path: ./build_output

      - id: create_release
        name: Create a release and upload the build
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ChapterMaster ${{ needs.gamemaker_build.outputs.suffix }}
          tag_name: dev/${{ github.ref_name }}
          prerelease: true
          generate_release_notes: true
          make_latest: true
          target_commitish: ${{ github.ref_name }}
          files: |
            ./build_output/${{ needs.gamemaker_build.outputs.built_file }}/*
